// Fill out your copyright notice in the Description page of Project Settings.

#pragma once
#include "NativeGameplayTags.h"

namespace BHopGameplayTags
{
	// Input Tags
	BHOPGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	BHOPGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	BHOPGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	BHOPGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipKatana);
	BHOPGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipKatana);
	BHOPGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_PrimaryAttack_Katana);

	// Player Tags
	BHOPGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Katana);
	BHOPGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Katana);
	BHOPGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Primary_Katana);
	BHOPGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);

	BHOPGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Katana);

	BHOPGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Katana);
	BHOPGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Katana);
	BHOPGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitPause);

	BHOPGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light);
	// Enemy Tags
	BHOPGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);

	BHOPGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);
	BHOPGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged);

	// Shared Tags
	BHOPGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	BHOPGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);

	BHOPGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);
	BHOPGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);

}